### ISSUE TITLE
relengapi irc bot

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#104]
Some notifications and operations might most easily be carried out via irc.

For example:

```
15:53 < relengapi > buildbot reconfig started; revisions buildbot=abcdef buildbot-configs=..
15:58 < relengapi > buildbot reconfig complete
```

or
```
08:23 < dustin > relengapi: disable bld-lion-r5-022
08:23 < relengapi > dustin: bld-lion-r5-022 disabled but still busy
08:57 < relengapi > dustin: bld-lion-r5-022 now idle
```

The read-only bits are pretty straightforward, but the opposite direction will need some careful thought regarding security.  Whitelisting irc nicks is probably not a sufficient form of authentication!

**Comment by djmitche** [comment]
@hwine I think what I was getting at here was something similar to chatops.  Thoughts?

**Comment by hwine** [comment]
I see 2 topics in the examples given: a) notifications (example 1) and b) irc initiated operations (example 2). I think of those as 2 separate features, especially in the realm of chat ops.

I do not think releng-api should grow into a "chat ops" solution (though it would be a major part of the back end). The issues of authentication, authorization, and business rule implementation are specialized enough to warrant a separate structure. At least that's what seems to be happening elsewhere.

I guess I'd always thought of relengapi as a http/rest based service. If there are clients that are irc based, that's fine. It's up to that client to re-broadcast anything significant.

**Comment by djmitche** [comment]
OK, that makes sense -- `y` will talk to relengapi as necessary to get information on what's going on and to initiate operations.  So there's not a lot to do here!
