### ISSUE TITLE
wsme API types may conflict across blueprints

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#147]
So if I have a relengapi.blueprints.slaveloan.rest.foo

And someone else does, for example relengapi.blueprints.clobberer.rest.foo both derived from wsme, then we'll have a naming conflict.

We should make the wsme type names relate to the module they are defined in, somehow.

Possible API compat issue.

**Comment by Callek** [comment]
I nominate as WONTFIX now that we have all blueprints in same repo, @djmitche do you concur?

**Comment by djmitche** [comment]
absolutely
