### ISSUE TITLE
Docs have no indexes

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#157]
This is actually a [Sphinx bug](https://bitbucket.org/birkenfeld/sphinx/issue/1003/using-websupport-how-do-i-get-the), so we wait until that's fixed.

**Comment by hwine** [comment]
sphinx move to github, blocking issue is now sphinx-doc/sphinx#1003

**Comment by Callek** [comment]
When the sphinx bug is fixed, we should backout PR #350
