### ISSUE TITLE
wsme bool input can emit True when unexpected

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#197]
In my use case I have an endpoint that takes url query params. This endpoint's param should accept boolean values (Null/None, 1, 0, True, False) and case insensitive at that...

While, the wsme framework will convert anything other than `""` and `None` python types to true, such that "0" and "false" are both True as per the endpoint.

I'm not sure the right way to fix this at this time though, so will address in my documentation for now.

**Comment by djmitche** [comment]
This isn't perl -- "0" and "false" are not false.  I don't find this surprising at all.

**Comment by djmitche** [comment]
There are `true` and `false` constants in JSON which should be used for Boolean values.

**Comment by djmitche** [comment]
Oh, derp, *query* params.

So you'd like

 * http://foo.com/bar?arg=  -> False
 * http://foo.com/bar?arg=0  -> False
 * http://foo.com/bar?arg=false  -> False
 * http://foo.com/bar?arg=true  -> True
 * http://foo.com/bar?arg=1  -> True

In which case this might best be filed as an upstream WSME bug.

**Comment by Callek** [comment]
Filed upstream as: https://bugs.launchpad.net/wsme/+bug/1493982
