### ISSUE TITLE
"logged in" notification should time out quickly

### ISSUE THREAD

**Issue by hwine** [mozilla/build-relengapi#204]
Log out is there in the menu, as per convention, but that big green rectangle is sure a pointer target. For an informational message, it attracts a lot of attention. I'd suggest either de-emphasize the rectangle or git it an action. The action I expected was "logout".

**Comment by djmitche** [comment]
Are you talking about the notification?  It goes away after a few seconds..

**Comment by hwine** [comment]
Big green rectangle in lower right - still there hours after I filed ;)
![screenshot 2015-03-31 13 53 20](https://cloud.githubusercontent.com/assets/132412/6929139/67641c66-d7ad-11e4-96af-0d64e1501a9f.png)

**Comment by djmitche** [comment]
gotcha, thanks
