### ISSUE TITLE
Use datestamps with sub-second accuracy on MySQL

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#216]
MySQL supports `datetime(6)` with six digits of subsecond accuracy, but the `UTCDateTime` class doesn't configure this setting by default.  That means we only get one-second accuracy on badpenny tasks, among other problems.

Ideally we could specify the precision for MySQL while not doing so for SQLite.

**Comment by Callek** [comment]
iirc reading docs, sqlite treats datetime as a string, so subsecond accuracy is not a problem there.

**Comment by djmitche** [comment]
I'm more worried about compatibility in `create table`
