### ISSUE TITLE
Allow regenerating a token, without changing the token

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#219]
I have no idea atm if this is even technically possible, BUT:

I can envision cases where we want to take an existing, known, token, and add (or remove) a permission from it without invalidating the whole token. This would allow "no perm" tokens, or "breaking change adds new permission" to add to a token.

The idea is the user would suppy the token string, and our api would validate it and grant new perms (or remove perms).

I don't think this idea deserves a full refactor of tokens though, so close out if that is required.

**Comment by djmitche** [comment]
It's not possible with temporary tokens, since they carry the permissions within them.

For usr and prm, it's possible -- the permissions are stored in the DB -- but I'm not sure it's wise.  I'd rather issue and deploy a new token in that case.

What's the use-case for altering the permissions of a token in-place without re-issuing?

**Comment by Callek** [comment]
one case I can think of is, "tree closure will make this service fragile, better to disable its permission" and "we deployed a new endpoint that this code uses, but this endpoint logically needs a new permission and we have this token already everywhere, lets make it easy by just adding the new permission to that token".

Basically its more an "ease of continual deployment" rather than a hard requirement. Since if a token is not leaked allowing the removal/adding is useful. I admittedly didn't think long on it (e.g. I'm not yet self-convinced, one way or the other, that the added complexity is worth it).

**Comment by djmitche** [comment]
Can you spell out the first usecase better?

In the second case, you would generate a new token and deploy that first.

**Comment by Callek** [comment]
say we know aws is going down for maint (or our link to it will break), we might disable the tooltool download permission temporarily so that automation only bothers to check from local cache's. or at least makes the cycle of attempt->failure faster (e.g. rather than wait 30 min, we can fail immediately during the closure).
