### ISSUE TITLE
Add contribute.json to all relengapi repos

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#224]
Similar to https://github.com/sylvestre/ship-it/blob/master/contribute.json -- this allows the project to be aggregated into https://mozilla.github.io/webdev/

**Comment by djmitche** [comment]
Just need to submit a PR against mozilla/webdev to list the project there.

**Comment by Callek** [comment]
All projects are now part of relengapi itself, closing

**Comment by djmitche** [comment]
Still needs a PR against webdev.  I should get around to that!

**Comment by djmitche** [comment]
https://github.com/mozilla/webdev/pull/24
