### ISSUE TITLE
Implement a notification system for production slaveloan when an admin needs to do manual work

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#247]
_From @Callek on May 14, 2015 18:57_

Right now there is no notification when an admin is awaiting manual work. There are many potential ways to implement this, SNS, nagios, e-mail, etc.

To determine at same time is if we want to do any early-warning systems like "jwood@m.c requested a loan of t-snow-r4-001" to #buildduty

_Copied from original issue: mozilla/build-relengapi-slaveloan#60_

**Comment by Callek** [comment]
Per a chat with coop/buildduty folks right now, we'd likely implement this as merely a logger message, that then papertrail will read and gets reported to us via SNS.

A future improvement on this may be a cron-like (badpenny) system that verifies these actions/steps haven't been waiting for too long a time.

This piece of work is primarily for getting the code to do the logging on the individual pieces (manual action created/pending) and if desired the "loan requested". Then additionally papertrail can be setup based on the live results of testing from staging.

**Comment by ciobancai** [comment]
After a chat with Callek on irc, we observed that the celery logs are sent to papertrail and I don't think is necessary to be implemented a cron to send the logs in papertrail. 

I used relengapi staging environment to test and I used the following query '(program:relengapi OR api-pub-build.allizom.org) is in need of a slaveloan from slavetype ' in papertrail to see the loan requests and worked, I was able to view my loan requests

**Comment by Callek** [comment]
the papertrail --> sms thing should be all we need here, indeed!

**Comment by ciobancai** [comment]
@Callek I would like to suggest to add also an email notification for me and Alin
