### ISSUE TITLE
Generate AWS machines when requested

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#255]
_From @Callek on March 31, 2015 4:59_

_Copied from original issue: mozilla/build-relengapi-slaveloan#43_

**Comment by ciobancai** [comment]
For the moment, we are using the following script "aws_create_instance.py" in order to create EC2 instances. I would like to ask if we can use the same script or do we need to create another script to do that from the scratch ?  
@Callek or @djmitche : what do you think ?

**Comment by Callek** [comment]
I think having to provide credentials that aws_create_instance.py could use would be a bit scary to me at the moment, so I would instead suggest we have relengapi contact slaveapi itself. which is the poorly documented docs at http://moz-releng-docs.readthedocs.org/projects/mozilla-slaveapi/en/latest/ and the code at https://dxr.mozilla.org/build-central/source/slaveapi (http://git.mozilla.org/?p=build/slaveapi.git)
