### ISSUE TITLE
Populate LDAP in loan requests by logged in user data

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#266]
_From @Callek on March 23, 2015 6:57_

Users requesting a loan should not be able to specify the LDAP name used, if we both are using the ldap login and they don't have the permission to do so.

c.f. https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26506641

_Copied from original issue: mozilla/build-relengapi-slaveloan#17_

**Comment by Callek** [comment]
fixed in issue #259
