### ISSUE TITLE
Be consistent about string formatting.

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#269]
_From @Callek on March 23, 2015 6:38_

At the least within same file, but ideally whole repo, we should be consistent with the following two python format styles::

``` python
"%s problem tracking" % slave_name,
"{slave_name} problem tracking".format(slave_name=slave_name)
```

We should probably use the latter to be more expressive throughout.

_Copied from original issue: mozilla/build-relengapi-slaveloan#13_

**Comment by wasifhyder** [comment]
Hi,

I'd like to get started on this. Any suggestions?

**Comment by djmitche** [comment]
Nothing more than above -- go for it!
