### ISSUE TITLE
Slaveloan needs a root widget

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#270]
_From @Callek on March 23, 2015 6:31_

We should add a root widget for slaveloan

c.f. https://github.com/mozilla/build-relengapi-slaveloan/pull/8#discussion_r26498099

_Copied from original issue: mozilla/build-relengapi-slaveloan#12_

**Comment by Callek** [comment]
this one was actually already fixed.... by https://github.com/mozilla/build-relengapi-slaveloan/issues/62
