### ISSUE TITLE
Consider using/recommending `hypothesis` for testing

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#294]
http://hypothesis.readthedocs.org/en/latest/

This seems similar to fuzzing, but perhaps a bit smarter.

It would be nice for, at least, testing API methods to ensure that they don't fail on weird inputs.

**Comment by rail** [comment]
There is an example in the docs: https://hypothesis.readthedocs.org/en/master/examples.html#fuzzing-an-http-api
