### ISSUE TITLE
validate.sh output should only colorize if output to tty

### ISSUE THREAD

**Issue by hwine** [mozilla/build-relengapi#320]
Reading the validate.sh output from a failed travis run is awkward due to all the escape sequences.

**Comment by djmitche** [comment]
Colorized output looks fine to me...

![screenshot from 2015-08-06 16 28 32](https://cloud.githubusercontent.com/assets/28673/9122617/3905a726-3c58-11e5-9360-85f5b126ef20.png)

**Comment by Callek** [comment]
huh last I looked at a failed travis run with validate.sh the escape sequences actually yielded color

**Comment by hwine** [comment]
Ah - I was having trouble navigating the view @djmitche posted, so went to the raw log. If it's working for y'all, I'll learn how to navigate. :)

**Comment by djmitche** [comment]
Yeah there's some funny business with the progress logging from pip.  I figure that's a Travis bug, since reloading fixed it :/
