### ISSUE TITLE
WSME-0.8 causes test failures in clobberer

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#325]

**Comment by djmitche** [comment]
https://github.com/stackforge/wsme/blob/master/doc/changes.rst suggests there is no 0.8.  

https://pythonhosted.org/WSME/ complains that I'm not looking at the docs for the latest release, but links me to that page.

http://packages.python.org/WSME/changes.html 404's

This is the level of "Kwalitee" you can expect from an OpenStack project, sadly.

**Comment by djmitche** [comment]
The errors from the clobberer tests are `relengapi.lib.testing.context: INFO: response: 400 BAD REQUEST - Unknown attribute for argument body: builddir (user='anonymous:' request_id='e0a84174-3aeb-44f7-897c-69845bcb9f66')`

**Comment by djmitche** [comment]
@mrrrgn do you mind taking a look at this?  It looks like this is a legit error: the tests pass `{"branch": "branch", "builddir": "builddir", "buildername": "buildername", "slave": "znork"}` to `/clobber/by-builder`, which expects a `ClobberRequestByBuilder`, which has fields `branch`, `builddername`, and `slave`  -- so `builddir` is superfluous and not allowed.  I'd just edit the tests, but that makes me nervous that I'm testing a bug.

**Comment by djmitche** [comment]
Note that the version of WSME required is pinned in f2006ee1; this should be un-pinned once this bug is fixed.

**Comment by Callek** [comment]
@mrrrgn how does this go?

I filed https://bugs.launchpad.net/wsme/+bug/1496958 for the documentation of changes missing, and https://github.com/stackforge/wsme/compare/0.7.0...0.8.0 has the full log for us.

https://github.com/stackforge/wsme/commit/6461c1b8a1dcb8820eeb32bbfbe8e3f22b3fa7ce looks like the cause of this issue, and has a good explanation for the change in the commit.
