### ISSUE TITLE
Bugzilla actions should use apikey instead of raw password

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#351]
So, our code currently uses user+password for bugzilla authorization.

https://github.com/mozilla/build-relengapi/blob/master/relengapi/blueprints/slaveloan/bugzilla.py

This apikey support was added into https://github.com/bhearsum/bzrest itself, and is available in bzrest 1.1, so we will need to bump the requirements:
https://github.com/mozilla/build-relengapi/blob/master/setup.py#L40

We also need to modify docs https://api.pub.build.mozilla.org/docs/deployment/slaveloan/#bugzilla

Once this piece deploys we need to modify the deployment config, and make sure it has the apikey (which is already generated and in our private repo)

**Comment by ciobancai** [comment]
Created pull request for the above changes #352

**Comment by Callek** [comment]
fixed by #352
