### ISSUE TITLE
clobberer not loading, just shows a template screen 

### ISSUE THREAD

**Issue by ewongbb** [mozilla/build-relengapi#371]
Logging on to the clobberer, I only get a template screen with two loading blue bars.
After waiting for ten minutes, it still doesn't load.  Looking at the error console I'm getting:

Timestamp: 4/5/2016 1:08:50 PM
Error: SyntaxError: missing ; after for-loop initializer
Source File: https://api.pub.build.mozilla.org/clobberer/static/clobberer.js
Line: 99, Column: 17
Source Code:
        for (let workerType in $scope.selectedTCBranch.workerTypes) { 

and

Timestamp: 4/5/2016 1:08:50 PM
Error: Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=clobberer&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.5%2F%24injector%2Fnomod%3Fp0%3Dclobberer%0AG%2F%3C%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A6%3A416%0Ade%2F%3C%2F%3C%2F%3C%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A24%3A78%0Aa%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A23%3A141%0Ade%2F%3C%2F%3C%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A23%3A1%0Ag%2F%3C%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A37%3A332%0An%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A7%3A320%0Ag%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A37%3A180%0Aeb%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A40%3A435%0Ayc%2Fd%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A19%3A381%0Ayc%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A20%3A179%0AZd%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A19%3A1%0A%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fangular%2Fangular.min.js%3A292%3A51%0Am.Callbacks%2Fj%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fjquery%2Fjquery-1.11.1.min.js%3A2%3A27239%0Am.Callbacks%2Fk.fireWith%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fjquery%2Fjquery-1.11.1.min.js%3A2%3A28057%0A.ready%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fjquery%2Fjquery-1.11.1.min.js%3A2%3A29889%0AJ%40https%3A%2F%2Fapi.pub.build.mozilla.org%2Fstatic%2Fjs%2Fjquery%2Fjquery-1.11.1.min.js%3A2%3A30255%0A
Source File: https://api.pub.build.mozilla.org/static/js/angular/angular.min.js
Line: 6

Both in SeaMonkey and Firefox.  In IE, it doesn't even load the template screen.

**Comment by djmitche** [comment]
Support for `let` was only added in Firefox 44 (released in January).  So perhaps you're using an older Firefox than that (yikes!!)?

Anyway, a PR to change `let` to `var` should fix this and would be appreciated :)

**Comment by djmitche** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
