### ISSUE TITLE
Add blueprint to support taskcluster scopes

### ISSUE THREAD

**Issue by jonasfj** [mozilla/build-relengapi#390]
We can find all permissions as follows:
```py
from relengapi.lib.permissions import p
all_perms = [perm for (perm, doc) in p]
```

And we can check with `auth.authenticateHawk` incoming request has scope: `relengapi:<permission>` for each permission, to decide if they are satisfied.

Then we create a `TaskclusterUser` and register an `auth.register_loader` that can load these if the `authorization` starts with "Hawk".

This way, all requests can be authorized with TC creds.

**Comment by jonasfj** [comment]
It might be as simple as something like this:
https://gist.github.com/jonasfj/5dc713ea4175da7bd066cfca89826cdc
I didn't test it, it was just a quick hack. The hard part is possible interaction with reverse proxy, which can obscure the port. As well as management of session and where to plug this in, if it's a blueprint or just a new built-in thing.

I might not be 100% up-to-date on python specifics, or how to write a blueprint, if that's even needed.
It might also be necessary to tweak `tokenauth` or ensure this runs first as it'll probably complain about the presences of an `'Authorization'` header that isn't a `'Bearer'` kind, see:
https://github.com/mozilla/build-relengapi/blob/807b4efe03409bf40c8a24f43210f11cb1a028c9/relengapi/blueprints/tokenauth/loader.py#L79-L84

**Comment by jonasfj** [comment]
With the `auth.request_loader` proposed above any request signed with taskcluster credentials (permanent or temporary alike) would have the releng-api `<permission>` if the credentials that signed the request have the scope `relengapi:<permission>`.

The motivation here is the ability to drop the relengapi-proxy in docker-worker. It requires all workers to have permanent releng-api tokens. That's bad for security and a nightmare to update. And we don't want to port relengapi-proxy to new workers. This way using `taskcluster-proxy` (available) on all workers tasks just need to have the scope `relengapi:<permission>` in `task.scopes`.

Furthermore, workers that don't operate on any task with such scopes would not have access to relengapi. As `task.scopes` are issued to workers by the queue with temporary credentials when the task is claimed.

**Comment by djmitche** [comment]
I think the gist looks good.  Likely it's best to modify the tokenauth loader so it just returns if it doesn't see "bearer", rather than try to carefully control the ordering of loaders.

It definitely makes sense to do this in a new blueprint.

**Comment by lundjordan** [comment]
> The motivation here is the ability to drop the relengapi-proxy in docker-worker. It requires all workers to have permanent releng-api tokens. That's bad for security and a nightmare to update.

Makes sense. However, we're close to switching over to relengapi replacement: https://github.com/mozilla-releng/services where we should get taskcluster auth for free. Relengapi EOL is end of June. Rok is back next week, and can tackle this first thing?

Given that, does it make sense to have a stop gap for ~2 weeks by putting perm creds in the worker? If not, the best person to review this patch is actually dustin as releng have traditionally had very little involvement with relengapi. Callek can also stamp but is less familiar.

**Comment by djmitche** [comment]
> releng have traditionally had very little involvement with relengapi. Callek can also stamp but is less familiar.

Well, relengapi is 100% releng.. it just got abandoned shortly after I moved to the TC team :)

**Comment by lundjordan** [comment]
> Well, relengapi is 100% releng.. it just got abandoned shortly after I moved to the TC team :)

True. But it's just the reality that you implemented most of this and it hasn't been touched since Rok started Services.

@Callek can look but he isn't familiar with a lot of the infra parts, including how auth/tokens work. if dustin and callek give a loose stamp, wfm.

This boils down to whether we can stop gap in docker-worker until June at latest (as Services replaces relengapi-proxy then) or whether we need to address this in relengapi now.

**Comment by djmitche** [comment]
Fair enough.  I am happy with the gist and can do a more thorough review / testing of a final patch, if that's what's required, and with Callek's second opinion.

**Comment by jonasfj** [comment]
> Makes sense. However, we're close to switching over to relengapi replacement: https://github.com/mozilla-releng/services where we should get taskcluster auth for free.

Oh, that's awesome... I think that we can easily "stop gap" until then. @walac already did a plugin for tc-worker adding relengapi-proxy :) so if this happening on it's own I'm going to close this.

If it's only weeks we could also just have put a relengapi token in tc-secrets... or taken some other detour.

**Comment by lundjordan** [comment]
adding @garbas to this thread and will raise this as a Services priority with him. He is back at the end of next week.

**Comment by garbas** [comment]
@jonasfj @djmitche  authentication and authorization via taskcluster is already implemented in services. it checks first for relengapi token in the header and has a fallback to taskcluster creds ([here](https://github.com/mozilla-releng/services/blob/master/lib/backend_common/backend_common/auth.py#L298-L305)).

As @lundjordan said I'm doing last bits of migration in next month (until SF all hands) if it is possible to wait until then you don't have to do anything except point to new urls.

HELP NEEDED: I would need help with testing migrated relengapi services that pass [relengapi-proxy](https://github.com/taskcluster/relengapi-proxy). Is there a staging instance for relengapi-proxy I could use for this? that way i could avoid closing down the trees like it happened last time.

**Comment by jonasfj** [comment]
The way it works `relengapi-proxy` is running on the workers, locally..

Are you changing the URLs for various API end-points? If not then it should just work, I suspect wcosta can help you configuring a docker-worker with a different relengapi-proxy token and setup, to see if that works.

But if you're maintaining the API end-points as before then probably this won't break anything. I almost assume you are, because otherwise everything in all trees would need to point at a different tooltool API :)

**Comment by garbas** [comment]
> @jonasfj commented:
> The way it works relengapi-proxy is running on the workers, locally..
> 
> Are you changing the URLs for various API end-points? If not then it should just work, I suspect wcosta can help you configuring a docker-worker with a different relengapi-proxy token and setup, to see if that works.
> 

yes, i'm changing the url. from https://api.pub.build.mozilla.org/<service> to https://<service>.mozilla-releng.net where <service> is one of: clobberer, mapper, tooltool, treestatus

> But if you're maintaining the API end-points as before then probably this won't break anything. I almost assume you are, because otherwise everything in all trees would need to point at a different tooltool API :)

every call to tooltool (via tooltool.py client) in tree already points to new URL, but every authenticated call to tooltool goes through relengapi-proxy which still [points to old url](https://github.com/taskcluster/relengapi-proxy/blob/master/main.go#L31).

I would like to avoid closing trees and to test new url on try running against "staging" release of relengapi-proxy which points to new url. at the same time "production" relengapi-proxy would still point to old.

I will ping @walac on IRC to help me. Tnx.

**Comment by garbas** [comment]
@walac @djmitche now that tooltool is running in new location (https://tooltool.mozilla-releng.net) you can use taskcluster credentials to authenticate with tooltool.

you can use the following function (https://github.com/mozilla-releng/services/blob/master/lib/backend_common/backend_common/auth.py#L280) to convert from relengapi permission to taskcluster scope. 

if you have any other question I would happy help. because once we move away from relengapi tokens more code is going to be removed and we all like to remove code :)
